# This rule is not used by the project edp-keycloak-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over v1.edp.epam.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize
  name: keycloakrealmrolebatch-admin-role
rules:
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmrolebatches
  verbs:
  - '*'
- apiGroups:
  - v1.edp.epam.com
  resources:
  - keycloakrealmrolebatches/status
  verbs:
  - get
