apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakClient
metadata:
  name: example-keycloakclient
spec:
  targetRealm: openshift
  secret: example-keycloakclient-secret
  clientId: some-another-client
  public: false
  directAccess: true
  webUrl: http://example-url
  protocol: openid-connect
  realmRoles:
    - name: sonar-admins
      composite: administrators
  clientRoles:
    - administrator
    - developer