apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloakRealm
metadata:
  labels:
    app.kubernetes.io/name: clusterkeycloakrealm
  name: clusterkeycloakrealm-sample
spec:
  clusterKeycloakRef: clusterkeycloak-sample
  realmName: realm-sample
  organizationsEnabled: false
  authenticationFlows:
    browserFlow: browserFlow-sample
