apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloakRealm
metadata:
  labels:
    app.kubernetes.io/name: clusterkeycloakrealm
    app.kubernetes.io/instance: clusterkeycloakrealm-sample
    app.kubernetes.io/part-of: edp-keycloak-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: edp-keycloak-operator
  name: clusterkeycloakrealm-sample
spec:
  clusterKeycloakRef: clusterkeycloak-sample
  realmName: realm-sample
  authenticationFlows:
    browserFlow: browserFlow-sample
