apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloak
metadata:
  labels:
    app.kubernetes.io/name: clusterkeycloak
  name: clusterkeycloak-sample
spec:
  secret: keycloak-access
  url: https://keycloak.example.com
