apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmUser
metadata:
  name: keycloakrealmuser-sample
spec:
  realmRef:
    name: keycloakrealm-sample
    kind: KeycloakRealm
  username: "john.snow13"
  firstName: "John"
  lastName: "Snow"
  email: "john.snow13@example.com"
  enabled: true
  emailVerified: true
  keepResource: true
  passwordSecret:
    key: password
    name: keycloakrealmuser-sample-password
    temporary: true
  requiredUserActions:
    - UPDATE_PROFILE
  attributesV2:
    department: ["IT"]
    location: ["Winterfell"]

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloakrealmuser-sample-password
type: Opaque
data:
  password: "U29tZVBhc3N3b3JkMTIzIQ==" # SomePassword123!
